services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgres/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY : ${SECRET_KEY}
      DEBUG : True
      DB_NAME : ${DATABASE_NAME}
      DB_USER : ${DATABASE_USER}
      DB_PASSWORD : ${DATABASE_PASSWORD}
      DB_HOST : ${DATABASE_HOST}
      DB_PORT : ${DATABASE_PORT}
    depends_on:
      - db

volumes:
  postgres_data: